### ISSUE TITLE
on Android, can't seem to edit a block after entering it

### ISSUE THREAD

**Issue by akavel** [gtg922r/obsidian-numerals#59]
I just installed Numerals in Obsidian on Android. I can enter a block with ` ```math ` and put some expressions in it; however, after I leave the block, I can't seem to be able to edit it anymore - I don't see the editing cursor, and the tools panel is in "viewing" mode (instead of "editing" mode + keyboard). When I click anywhere outside the math block, I can still edit normally. Am I doing something wrong? Or is it a bug?

Obsidian Android version: 1.4.6 (105)
API v1.3.3
Numerals version: 1.2.0

**Comment by duxswhatdux** [comment]
The same happens on IOS. You need to place the cursor under the rendered block, backspace to display the code block. Often I’ll keep a few spaces below a code block and between other text below it for this vey reason on the mobile app.

**Comment by gtg922r** [comment]
Unfortunately I believe this is an obsidian limitation, and you need to follow the above suggestion. 

Closing as wontfix. If this is a Numerals specific issue, please re-open

**Comment by andersfischernielsen** [comment]
I faced the same issue and started looking into what the differences are on desktop vs. mobile. 

On desktop, there’s an “Edit this block” button that appears in the top right of a rendered math block on mouseover. 
This button is still present on mobile, but is hidden since mouseover isn’t a thing on touch screens. 

Clicking/tapping the top right of a rendered component still enters edit mode even if the button isn’t showing, though!

So the workaround on mobile is to tap the top right of a rendered block to edit it. No need for extra blank lines after every math block. 😄
